name: Publish Release to NPM - Github package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - run: npm install

      # Publish to GitHub Packages
      - run: npm publish
